In [4]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [5]:
## load ann trained model sclr pkl ohe lab 
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [6]:
with open('lable_encoder_gender.pkl','rb') as file1:
    laber_gender = pickle.load(file1)

with open('OneHotEncoder_geo.pkl','rb')as file2:
    one_hot_geo = pickle.load(file2)

with open('scaler.pkl','rb') as file3:
    scaled_opp = pickle.load(file3)

In [25]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}
input_df = pd.DataFrame([input_data])

In [14]:
geo_encoder = one_hot_geo.transform([[input_data['Geography']]]).toarray()

c:\Users\maith\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [20]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns=one_hot_geo.get_feature_names_out(['Geography']))

In [26]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [29]:
input_df = pd.concat([input_df.reset_index(drop=True),geo_encoded_df],axis=1)

In [30]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [31]:
input_df['Gender']=laber_gender.transform(input_df['Gender'])

In [34]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [33]:
input_df.drop('Geography',axis=1,inplace=True)

In [35]:
scalling = scaled_opp.transform(input_df)

In [36]:
scalling

array([[-0.54007722,  0.91186722,  0.10685843, -0.69164931, -0.26034447,
         0.81311138,  0.64946204,  0.96978946, -0.88017893,  1.00053348,
        -0.57776083, -0.57735027]])

In [39]:
## prediction 
pred =model.predict(scalling)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

In [40]:
prediction_prob = pred[0][0]

In [41]:
prediction_prob

np.float32(0.031643678)

In [ ]:
if prediction_prob > 0.5:
    print('The Customer is likely to churn')
else:
    print('The Customer is not likely to churn')

The Customer is not likely to churn

In [1]:
import streamlit as slt